#!/usr/bin/env bash
# A Bash script must accept 2 arguments
get_record_info() {
    local domain="$1"
    local subdomain="$2"
    local record_type="$3"
    
    if [ -z "$subdomain" ]; then
        subdomains=("www" "lb-01" "web-01" "web-02")
    else
        subdomains=("$subdomain")
    fi
    
    for sub in "${subdomains[@]}"; do
        record=$(dig "$sub.$domain" | awk -v type="$record_type" '$4 == type {print $5}')
        echo "The subdomain $sub is a $record_type record and points to $record"
    done
}

domain="$1"
subdomain="$2"
get_record_info "$domain" "$subdomain" "A"
